name: Build project

on: [push, pull_request]
jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit 
          - WebGL # WebGL.standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
  - uses: game-ci/unity-builder@v2.1.2
env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  with:
    targetPlatform: ${{ matrix.targetPlatform }}
- uses: actions/upload-artifact@v2
  with:
    name: Build
    path: build
- uses: game-ci/unity-builder@v2.1.2
  with:
    versioning: Semantic